networks:
  d_network:
    name: d_network
    driver: bridge

services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: d_app
    restart: "no"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - d_network
    command: 
      sh -c "uv run uvicorn --factory main:create_app --host 0.0.0.0 --port 8000"
  
  db:
    image: postgres:17-alpine3.20
    container_name: d_db
    restart: "no"
    env_file:
      - .env
    networks:
      - d_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
