"""changed payments

Revision ID: 205bb8993992
Revises: 9e7f7b272427
Create Date: 2025-03-08 02:37:58.155536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205bb8993992'
down_revision: Union[str, None] = '9e7f7b272427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=256), nullable=False))
    op.add_column('payments', sa.Column('signature', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'payments', ['signature'])
    op.create_unique_constraint(None, 'payments', ['transaction_id'])
    
    # add mok data
    op.execute("""
        INSERT INTO users (id, name, last_name, email, password, is_admin)
        VALUES
        (1, 'John', 'Doe', 'user@example.com', 'f07360a0548a58ceaa02c9960e91e03649fb37d17bfd8e95c5f1fa388c24e2f0', true),
        (2, '1John', '1Doe', '1user@example.com', 'f07360a0548a58ceaa02c9960e91e03649fb37d17bfd8e95c5f1fa388c24e2f0', false);
    """)
    op.execute("""
        INSERT INTO invoices (id, user_id, balance)
        VALUES 
        (1, 1, 1000),
        (2, 2, 5000);
    """)
    op.execute("""
        INSERT INTO payments (id, invoice_id, transaction_id, amount, signature)
        VALUES
        (1, 1, '5eae174f-7cd0-472c-bd36-35660f00132b', 1000, '7b47e41efe564a062029da3367bde8844bea0fb049f894687cee5d57f2858bc8');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    #clean mok data
    op.execute("DELETE FROM payments;")
    op.execute("DELETE FROM invoices;")
    op.execute("DELETE FROM users;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'signature')
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
